
#nombre de configuración
name: API mongo-express

# accion que detonan los jobs CI
on: [push, pull_request]

# las tareas que se van a ejecutar
jobs:

  # Compilar nuestro proyecto  
  build:

    # Define sobre que SO se va a compilar
    runs-on: ubuntu-latest

    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }}  server hosted by GitHub!"
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Build Docker image  # nombre del proceso 
        uses: actions/checkout@v3 # version de github actions que vamos a usar
      - run: docker build .  --file Dockerfile --tag api-v1
     
  # Instrucciones para ejecutar los test
  test:
    
    # Define sobre que SO se va a compilar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: backend tests
        uses: actions/setup-node@v3
          with:
            node-version: '12.x'
            
      # Similiar a npm install
      - run: npm ci 
      - run: npm test 






